### ISSUE TITLE
Svg rect associated with Logo image is infinitely proliferated 

### ISSUE THREAD

**Issue by satotake** [times/cardkit#45]
Hi, Thank you for the nice tool.

[environment]
- Mac ver: 10.10.5
- Chrome ver: 50.0.2661.102

[specification]
- If logo img is hovered, a svg rect is prepended. 
- If logo img is unhovered, the rect is removed.

[issue]
If logo is mousedown-ed and mouseup-ed outside logo by moving the cursor horizontally, 
the svg rect is not removed and this results in inifinite proliferation of the rect

![2016-06-03 11 47 04](https://cloud.githubusercontent.com/assets/9415800/15767663/f1e8922a-2984-11e6-9e5d-2eb69f382734.png)

![2016-06-03 11 47 19](https://cloud.githubusercontent.com/assets/9415800/15767666/ff2649c8-2984-11e6-99ca-ed4907579845.png)

**Comment by chrishutchinson** [comment]
Fixed by merging PR #46 - many thanks @satotake!

**Comment by UNFPAmaldives** [comment]
This issue persists in 1.1.1 — not for the logo, but rather for the headline — when running Firefox 48.0.1 on OSX 10.11.6.
